chore: automated installer/zip on release tags
elanthia-online/lich-5 pull request #305
Opened 2023-02-23 20:31 UTC by mrhoribu

Automatically create an Inno Setup installer on a new release tag matching `v*.*.*` and add just core Lich-5 files to a zip/tarball for download as well.

2023-02-23 21:34 UTC, mrhoribu commented
Implements and closes #199

2023-02-23 21:35 UTC, mrhoribu commented
Also resolves #289

2023-02-23 23:10 UTC, ondreian requested changes
almost there!

2023-02-23 23:10 UTC, ondreian commented on .gitignore
> +R4LGTK3.iss
this should include `scripts/` and `data/` now

2023-02-23 23:11 UTC, ondreian approved these changes
lgtm

2023-02-24 12:59 UTC, OSXLich-Doug approved these changes
All in on this - remember to update the GUID with each major Ruby rev!

2023-02-24 13:58 UTC, ondreian commented
what GUID? We can probably just make this match the git hash of the last
commit in the release, so it's got 1-to-1 relationship there?

On Fri, Feb 24, 2023, 05:59 OSXLich-Doug ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> All in on this - remember to update the GUID with each major Ruby rev!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/elanthia-online/lich-5/pull/305#pullrequestreview-1313380804>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIKHAVQYAM2OYEDDBAJNFTWZCWCRANCNFSM6AAAAAAVGC6YO4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-02-26 21:10 UTC, OSXLich-Doug commented
Yeah, that might work.  GUID is in the innosetup script used to compile the
build.

On Fri, Feb 24, 2023 at 8:58 AM Benjamin Clos ***@***.***>
wrote:

> what GUID? We can probably just make this match the git hash of the last
> commit in the release, so it's got 1-to-1 relationship there?
>
> On Fri, Feb 24, 2023, 05:59 OSXLich-Doug ***@***.***> wrote:
>
> > ***@***.**** approved this pull request.
> >
> > All in on this - remember to update the GUID with each major Ruby rev!
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/elanthia-online/lich-5/pull/305#pullrequestreview-1313380804
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAIKHAVQYAM2OYEDDBAJNFTWZCWCRANCNFSM6AAAAAAVGC6YO4
> >
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/elanthia-online/lich-5/pull/305#issuecomment-1443716502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEG5B4YHH5ZKGF7UY6KYL33WZC47FANCNFSM6AAAAAAVGC6YO4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-02-28 15:51 UTC, mrhoribu commented
Hmm, need to figure out how to automate the new GUID creation and if it can be passed as a CLI option since the GUID is part of the config file. Wouldn't want to have to remember to update the GUID manually every time a new release is made.

> All in on this - remember to update the GUID with each major Ruby rev!

2023-03-12 21:46 UTC, merged